title: CSCI-UA.0060 Fall 2020, Section 001

baseurl: ""
resource_prefix: "resources/"
github_username: jversoza
slides_lib: "../../resources/lib"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot
permalink: none
exclude: [bower_components, README.md, bower.json, gruntfile.js, node_modules]

vars:
  survey_github: ""
  forums: "https://campuswire.com/"
  email: "jversoza at cs dot nyu dot edu"
  slides_img_prefix: "../../resources/img"
  
  # course
  course_number: "CSCI-UA.0060"
  course_section: "001"
  course_name: "Database Design and Implementation"
  course_semester: "Fall 2020"
  course_time: "T and TH, 12:30PM-1:45PM"
  course_room: "Remote"
  course_site: https://cs.nyu.edu/courses/fall20/CSCI-UA.0060-001/ 
  course_site_alt: http://cs.nyu.edu/~jversoza
  
  # office hours
  office_hours: "<br>TBD"
  office_hours_room: WWH 422
  
  # midterm
  midterm1_date: "N/A"
  midterm1_time: "N/A"
  
  # finals
  final_date: "N/A"
  final_time: "N/A"
  final_room: "N/A"
  
  book_python_full: "Python for Everybody: Exploring Data Using Python 3"
  book_python: "py4e"
  book_python_link: "https://www.py4e.com/html3/"
  book_python_author: "Charles Severance"

  book_data_full: "Bad Data Handbook"
  book_data: "Bad Data Handbook"
  book_data_link: "https://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph005835927&context=L&vid=NYU&lang=en_US"
  book_data_author:  "Q. Ethan McCallum"
  
  book_sqlite_full: "Using SQLite"
  book_sqlite: "Using SQLite"
  book_sqlite_link: "https://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph007031845&context=L&vid=NYU&lang=en_US"
  book_sqlite_author: "Jay A. Kreibich"

  book_db_design_full: "Database Design "
  book_db_design: "Database Design "
  book_db_design_link: "https://opentextbc.ca/dbdesign01/"
  book_db_design_author: "Adrienne Watt (primary author)"
  
  book_mysql_full: "Learning MySQL and MariaDB: heading in the right direction with MySQL and MariaDB "
  book_mysql: "Learning MySQL and MariaDB"
  book_mysql_link: "https://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph005573381&context=L&vid=NYU&lang=en_US"
  book_mysql_author: "Russell J. T. Dyer"

  book_mongodb_full: "MongoDB Manual"
  book_mongodb: "MongoDB Manual"
  book_mongodb_link: "https://docs.mongodb.com/manual/introduction/"

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
